spring:
  application:
    name: docling-rag

  ai:
    ollama:
      init:
        pull-model-strategy: when-missing
      chat:
        model: granite4:3b
      embedding:
        model: granite-embedding:278m

    vectorstore:
      pgvector:
        dimensions: 768
        index-type: hnsw
        initialize-schema: true

arconia:
  dev:
    services:
      postgresql:
        image-name: pgvector/pgvector:pg18
